config/routes.rb
Rails.application.routes.draw do
  resources :activities

   root 'activities#index'

  get '/about' => 'application#about'
  get '/contact' => 'application#contact'
  get '/clear_activities' => 'activities#clear_activities'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_type

  default_value_for :curr_date do
    Date.today
  end

  scope :fetch_all_open_activity, -> { where(end_time: nil).joins(:activity_type).where.not(activity_types: { name: 'IN-OFFICE' }) }
  scope :fetch_in_office_activity, -> { where(curr_date: Date.today).where(end_time: nil).joins(:activity_type).where(activity_types: { name: 'IN-OFFICE' }) }

  def save_and_close_prev(time)
    curr_activity = Activity.fetch_current_activity
    curr_activity.close(time) unless curr_activity.nil? || curr_activity.is_overlapping_allowed
    Activity.create_in_office(self.start_time)
    self.duration=1
    self.save
  end

  def self.create_in_office(start_time)
    in_office_activity = Activity.fetch_in_office_activity
    if in_office_activity.nil? then
      in_office_activity = Activity.new
      in_office_activity.start_time= start_time
      in_office_activity.activity_type = ActivityType.get_in_office_activity
      in_office_activity.save
    end
  end

  def close(end_time)
    self.end_time = end_time
    self.duration = calculate_duration(self.start_time, self.end_time)
    self.save
  end

  def update_activity(params)
    self.end_time = params[:end_time]
    self.duration = calculate_duration(self.start_time, self.end_time)
    self.save_and_close_prev(self.end_time)
    self.update(params)
  end

  def self.fetch_current_activity
    fetch_all_open_activity.first
  end

  def is_overlapping_allowed
    self.activity_type.overlapping
  end

  def activity_name
    if self.activity_type.nil? then
      'No Activity'
    else
      self.activity_type.name
    end
  end

  def activity_start_time
    if self.start_time.nil? then
      '-'
    else
      self.start_time.strftime("%H:%M (Hour:Min)")
    end
  end

  def self.activity_summary
    Summary.new
  end

  private
  def calculate_duration(start_time, end_time)
    ((end_time - start_time) / 1.minute).round
  end
end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base

  has_many :activities

  scope :all_but_in_office, -> { where.not(name: 'IN-OFFICE') }
  scope :get_in_office_activity, -> { where(name: 'IN-OFFICE') }

end

app/models/summary.rb
class Summary

  attr_accessor :activity_duration, :timeline
  def initialize
    today = Date.today
    @activity_duration = Activity.joins(:activity_type).where(["curr_date = ? and activity_type_id <> 9", today]).group('activity_types.name').sum(:duration)
    @total_hours_worked = Activity.where(["curr_date = ? and activity_type_id <> 9", today]).sum(:duration)
    @in_office_by = Activity.joins(:activity_type).where(["curr_date = ? and name = ?", today, "IN-OFFICE"]).first
    @timeline = Activity.includes(:activity_type).joins(:activity_type).where(["curr_date = ? and end_time is not null and activity_type_id <> 9", today]).load.map{|activity| [activity.activity_name, activity.start_time, activity.end_time]}
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    set_index_vals
  end

  def set_index_vals
    @activity = Activity.new
    @activity_types = ActivityType.all_but_in_office
    @current_activity=Activity.fetch_current_activity
    @activity_chart=Activity.activity_summary
    @in_office_activity=Activity.fetch_in_office_activity
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    index
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    respond_to do |format|
      if @activity.save_and_close_prev(@activity.start_time)
        set_index_vals
        format.html { render :index }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update_activity(activity_params)
        set_index_vals
        format.html { render :index }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def clear_activities
    Activity.delete_all
    set_index_vals
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:start_time, :end_time, :activity_type_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # /about
  def about

  end

  # /contact
  def contact

  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def get_activity_name(activity)
    return 'No Activity' if activity.nil?
    activity.activity_name
  end

  def get_activity_start_time(activity)
    return '-' if activity.nil?
    activity.activity_start_time
  end

  def draw_timeline_chart(time_line)
    if time_line.size == 0
      chart_data = [['NO-DATA', '00:00'.to_time, '01:00'.to_time]]
    elsif
      chart_data = time_line
    end
    timeline chart_data
  end

  def draw_summary_chart(activity_duration)
    if activity_duration.size == 0
      chart_data = {'NO-DATA' => 30}
    elsif
      chart_data = activity_duration
    end
    pie_chart chart_data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, :html => {:id => 'activity_form'} do |f| %>
    <p>
      <span class="field clearfix">
        <span>
        <small>Start Hour:</small>
        <input type="text" id="hours" placeholder="HH" class="width-35"/>
          </span>
        <span>
          <small>Start Min:</small>
        <input type="text" id="min" placeholder="mm" class="width-35"/>
          </span>
        <%= f.hidden_field :start_time, :id => 'start_time'%>
        </span>
    </p>
    <p>
    <span class="field">
      <small>Type (1 - 8):</small>
      <%= f.collection_select(:activity_type_id, @activity_types, :id, :name, prompt: true) %>
    </span>


    </p>

<% end %>

app/views/activities/_in_office_form.html.erb
<%= form_for @in_office_activity.first, :html => {:id => 'in_office_form'} do |f| %>
    <p>
      <span class="field clearfix">
        <span>
        Leave Hour:
        <input type="text" id="office_hours" placeholder="HH" class="width-35"/>
          </span>
        <span>
          Min:
        <input type="text" id="office_min" placeholder="mm" class="width-35"/>
          </span>
        <%= f.hidden_field :end_time, :id => 'office_end_time'%>
        </span>
    </p>

<% end %>

app/views/activities/_show.html.erb
<%= form_for(activity) do |f| %>
    <blockquote>
      <p>
        <small>Start:</small>
        <%= activity.start && activity.start.strftime("%H:%M (Hour:Min)") %>
      </p>

      <% if activity.is_overlapping_allowed %>
          <p>
            <small>End:</small>
    <span class="field">
      <%= f.text_field :end_time, :autofocus => true %>
      <%= f.label "hh:mm" %><br>
    </span>
          </p>
      <% end %>
      <p>
        <small>Type:</small>
        <%= activity.activity_name %>
      </p>
      <div class="actions">
        <%= f.submit %>
      </div>
    </blockquote>
    <hr/>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <title>The Good Tracker</title>
</head>

<body>

<div class="container">
  <div class="header clearfix">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation" class="active"><a href="#">Home</a></li>
        <li role="presentation"><a href="/about">About</a></li>
        <li role="presentation"><a href="/contact">Contact</a></li>
      </ul>
    </nav>
    <h3 class="text-muted">The Good Tracker</h3>
  </div>

  <div class="row marketing">
    <div class="col-lg-6 height-300 left">
      <%= draw_summary_chart(@activity_chart.activity_duration) %>
    </div>
    <div class="col-lg-6 height-300 right">
      <%= draw_timeline_chart(@activity_chart.timeline) %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 left top-10">
      <div class="well">
        Your are currently in <code> <%= get_activity_name(@current_activity) %></code>
        from <%= get_activity_start_time(@current_activity) %>
      </div>
    </div>
    <div class="col-lg-6 pull-right top-10">
      <div class="well">
        <span>You are in <code>Office</code> from <%= get_activity_start_time(@in_office_activity.first) %></span>
        <span class="inline-form"><%= render 'in_office_form' unless @in_office_activity.blank? %></span>
      </div>
    </div>
  </div>
  <div class="row margin-10">
    <div class="col-lg-offset-2 col-lg-8 panel panel-default">
      <div class="col-lg-offset-2 col-lg-8 panel-body pad-10">
        <div class="text-center">
          <h4>Enter your activity :</h4>
          <%= render 'form' %>
        </div>
        <table class="table table-striped small-font">
          <tr>
            <td>1. DEV-HUDDLE</td>
            <td>2. PET-PROJECT</td>
            <td>3. PAIRING</td>
            <td>4. STAND-UP</td>
          </tr>
          <tr>
            <td>5. MEETING</td>
            <td>6. TT</td>
            <td>7. NOTHING</td>
            <td>8. READING-NEWS</td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <footer class="footer">
    <p>&copy; 2015 Company, Inc.</p>
  </footer>

</div>
<!-- /container -->
</body>
</html>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show', activity: @activity %>
<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Daytracker</title>
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>

</html>